In [2]:
! pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.43)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.14.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=0e1a0d06101cd7c02ea4a3297e1b3c5db011f8cb1806b4c60e8a5e8119a99a9b
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [ ]:
import os
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
url = "https://raw.githubusercontent.com/syntagmatic/gapminder-csv/refs/heads/master/gapminder.csv"
df = pd.read_csv(url)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79309 entries, 0 to 79308
Columns: 537 entries, geo to yearly_co2_emissions_1000_tonnes
dtypes: float64(535), int64(1), object(1)
memory usage: 324.9+ MB

In [7]:
sqldf("SELECT * FROM df LIMIT 5") #columnas a trabajar: children_per_woman_total_fertility life_expectancy_years

,geo,time,adults_with_hiv_percent_age_15_49,age_at_1st_marriage_women,aged_15_24_employment_rate_percent,aged_15_24_unemployment_rate_percent,aged_15_64_labour_force_participation_rate_percent,aged_15plus_employment_rate_percent,aged_15plus_labour_force_participation_rate_percent,aged_15plus_unemployment_rate_percent,...,underweight_children,urban_population,urban_population_growth_annual_percent,urban_population_percent_of_total,urban_poverty_percent_urban_people_below_national_urban,water_and_sanitation_aid_given_percent_of_aid,water_withdrawal_cu_meters_per_person,wood_removal_cubic_meters,working_hours_per_week,yearly_co2_emissions_1000_tonnes
0,afg,1700,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,afg,1800,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,afg,1801,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,afg,1802,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,afg,1803,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [9]:
# sqldf("SELECT children_per_woman_total_fertility, life_expectancy_years FROM df LIMIT 10")
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df LIMIT 10")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  afg  1700                                 NaN                    NaN
1  afg  1800                                 7.0                  28.21
2  afg  1801                                 7.0                  28.20
3  afg  1802                                 7.0                  28.19
4  afg  1803                                 7.0                  28.18
5  afg  1804                                 7.0                  28.17
6  afg  1805                                 7.0                  28.16
7  afg  1806                                 7.0                  28.15
8  afg  1807                                 7.0                  28.14
9  afg  1808                                 7.0                  28.13

In [11]:
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo='arg' and time > 1975 LIMIT 10")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  arg  1976                                3.37                  67.76
1  arg  1977                                3.39                  68.20
2  arg  1978                                3.39                  68.84
3  arg  1979                                3.37                  69.38
4  arg  1980                                3.33                  69.85
5  arg  1981                                3.27                  70.16
6  arg  1982                                3.21                  70.55
7  arg  1983                                3.16                  70.62
8  arg  1984                                3.12                  70.93
9  arg  1985                                3.09                  71.33

In [12]:
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo='col' and time > 1980 LIMIT 10")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  col  1981                                3.86                  69.43
1  col  1982                                3.74                  69.97
2  col  1983                                3.63                  70.16
3  col  1984                                3.53                  70.58
4  col  1985                                3.42                  68.00
5  col  1986                                3.32                  70.60
6  col  1987                                3.23                  70.58
7  col  1988                                3.14                  70.80
8  col  1989                                3.07                  70.96
9  col  1990                                2.99                  71.38

In [14]:
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo IN ('col','arg') AND time = 2000")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  arg  2000                                2.56                  74.21
1  col  2000                                2.39                  73.25

In [15]:
sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years FROM df WHERE geo IN ('col','arg','mex') AND time = 2000")

   geo  time  children_per_woman_total_fertility  life_expectancy_years
0  arg  2000                                2.56                  74.21
1  col  2000                                2.39                  73.25
2  mex  2000                                2.72                  74.61

In [16]:
sqldf("SELECT DISTINCT geo FROM df")

             geo
0            afg
1            ago
2            arg
3            arm
4            aus
..           ...
259    yem_south
260          yug
261  korea_union
262          maf
263        world

[264 rows x 1 columns]

In [18]:
sqldf("SELECT geo, time, gdp_total_yearly_growth FROM df WHERE geo= 'per' AND time BETWEEN 1985 AND 2000")

    geo  time  gdp_total_yearly_growth
0   per  1985                  2.03300
1   per  1986                 10.08000
2   per  1987                  8.61900
3   per  1988                 -8.18500
4   per  1989                -12.21000
5   per  1990                 -5.13500
6   per  1991                  2.39300
7   per  1992                 -1.05400
8   per  1993                  5.49200
9   per  1994                 13.35000
10  per  1995                  8.37600
11  per  1996                  2.14600
12  per  1997                  8.49600
13  per  1998                  0.04935
14  per  1999                  0.87260
15  per  2000                  3.04900

In [19]:
sqldf("SELECT geo, time, gdp_total_yearly_growth FROM df WHERE geo= 'per' AND time BETWEEN 1985 AND 2000 ORDER BY time DESC")

    geo  time  gdp_total_yearly_growth
0   per  2000                  3.04900
1   per  1999                  0.87260
2   per  1998                  0.04935
3   per  1997                  8.49600
4   per  1996                  2.14600
5   per  1995                  8.37600
6   per  1994                 13.35000
7   per  1993                  5.49200
8   per  1992                 -1.05400
9   per  1991                  2.39300
10  per  1990                 -5.13500
11  per  1989                -12.21000
12  per  1988                 -8.18500
13  per  1987                  8.61900
14  per  1986                 10.08000
15  per  1985                  2.03300

In [20]:
sqldf("SELECT geo, time, gdp_total_yearly_growth FROM df WHERE geo= 'arg' AND time BETWEEN 1990 AND 2010 ORDER BY time DESC")

    geo  time  gdp_total_yearly_growth
0   arg  2010                   8.8850
1   arg  2009                   0.5982
2   arg  2008                   6.4950
3   arg  2007                   8.3880
4   arg  2006                   8.2050
5   arg  2005                   9.0800
6   arg  2004                   8.8820
7   arg  2003                   8.7560
8   arg  2002                 -11.1200
9   arg  2001                  -4.5230
10  arg  2000                  -0.8075
11  arg  1999                  -3.3760
12  arg  1998                   3.9930
13  arg  1997                   8.3440
14  arg  1996                   5.7560
15  arg  1995                  -2.6960
16  arg  1994                   6.1230
17  arg  1993                   6.0380
18  arg  1992                  10.0100
19  arg  1991                  10.8000
20  arg  1990                  -1.8520

In [23]:
sqldf("SELECT MAX(gdp_total_yearly_growth) AS max_gdp FROM df WHERE geo='mex'")

   max_gdp
0    12.22

In [24]:
sqldf("SELECT MAX(gdp_total_yearly_growth) AS max_gdp, geo FROM df GROUP BY geo LIMIT 20")

    max_gdp        geo
0       NaN       abkh
1     18.76        abw
2     28.28        afg
3     23.19        ago
4     24.56        aia
5       NaN  akr_a_dhe
6       NaN        ala
7     11.80        alb
8     12.99        and
9     36.37        ant
10   189.70        are
11    26.76        arg
12    17.74        arm
13    19.46        asm
14    12.65        atg
15    33.70        aus
16    27.33        aut
17    34.60        aze
18    26.27        bdi
19    57.92        bel

In [26]:
sqldf("SELECT MAX(gdp_total_yearly_growth) AS max_gdp, time, geo FROM df WHERE geo IN ('arg','per','mex') GROUP BY geo LIMIT 20")

   max_gdp  time  geo
0    26.76  1882  arg
1    12.22  1950  mex
2    13.83  1960  per

In [29]:
sqldf("SELECT MAX(gdp_total_yearly_growth) AS max_gdp, time, geo FROM df WHERE geo IN ('arg','per','mex') AND time >= 1985 GROUP BY geo ")

   max_gdp  time  geo
0   10.800  1991  arg
1    7.087  1997  mex
2   13.350  1994  per

In [30]:
sqldf("SELECT MIN(gdp_total_yearly_growth) AS min_gdp, time, geo FROM df WHERE geo IN ('arg','per','mex') AND time >= 1985 GROUP BY geo ")

   min_gdp  time  geo
0   -11.12  2002  arg
1    -6.40  1995  mex
2   -12.21  1989  per

In [37]:
my_df = sqldf("SELECT geo, time, children_per_woman_total_fertility, life_expectancy_years, gdp_total_yearly_growth FROM df WHERE geo IN ('usa','bra','jpn') AND time > 1975 AND life_expectancy_years IS NOT NULL AND gdp_total_yearly_growth IS NOT NULL ORDER BY geo")

In [38]:
my_df

,geo,time,children_per_woman_total_fertility,life_expectancy_years,gdp_total_yearly_growth
0,bra,1976,4.42,64.12,10.350
1,bra,1977,4.34,64.64,4.892
2,bra,1978,4.26,65.11,4.925
3,bra,1979,4.17,65.54,6.755
4,bra,1980,4.07,65.86,9.634
...,...,...,...,...,...
109,usa,2009,2.00,78.56,-3.482
110,usa,2010,1.93,78.74,2.876
111,usa,2011,1.90,78.83,1.990
112,usa,2012,1.90,78.91,2.938
113,usa,2013,1.96,78.93,2.031